#!/bin/bash
#SBATCH --mem 5G  # Requested Memory
#SBATCH -p gpu  # Partition
#SBATCH -G 1  # Number of GPUs
#SBATCH --constraint m40
#SBATCH -t 12:00:00  # Job time limit
#SBATCH -o slurm-%j.out  # %j = job ID

module load cuda/11.8
#nvcc --version 
python main_baseline.py
